baseURL: "https://yaheya.github.io/pulse/"
languageCode: en-us
title: Pulse
theme: PaperMod

menu:
  main:
    - identifier: categories
      name: Categories
      url:  /categories/
      weight: 10

